const STORAGE_KEYS={bookings:"egmond_bookings_v7",requests:"egmond_requests_v7"};
const HERO_IMAGES=["images/header_neu.jpg","images/Header_fenster.jpg","images/header_duenen.jpg","images/Header_strandkorb.jpg"];
const PHOTOS=[
  {img:"images/header_neu.jpg",caption:"Außenansicht"},
  {img:"images/Egmond Fenster.jpg",caption:"Fensterblick"},
  {img:"images/Egmond Sonnenuntergang.jpg",caption:"Sonnenuntergang"},
  {img:"images/Egmond app (1).jpeg",caption:"Wohnbereich"},
  {img:"images/Egmond app (2).jpeg",caption:"Essbereich"},
  {img:"images/Egmond app (3).jpeg",caption:"Schlafzimmer"},
  {img:"images/Egmond app (4).jpeg",caption:"Küche"},
  {img:"images/Egmond app (5).jpeg",caption:"Bad"},
  {img:"images/Egmond Abend.jpg",caption:"Abendstimmung"}
];
const DEFAULT_BOOKINGS=[
  {id:"b1",label:"Schmidt",start:"2026-03-16",end:"2026-03-21",type:"full"},
  {id:"b2",label:"Meyer",start:"2026-03-28",end:"2026-04-03",type:"arrival-departure"},
  {id:"b3",label:"Becker",start:"2026-04-18",end:"2026-04-23",type:"full"}
];
const BRIDGE_DAYS={
  2026:["2026-01-02","2026-05-15","2026-06-05"],
  2027:["2027-05-07","2027-05-28"],
  2028:["2028-05-26","2028-06-16","2028-10-02"]
};
const SPECIAL={school:new Set(),holiday:new Set(),bridge:new Set()};
const state={monthOffset:0,selectedArrival:null,selectedDeparture:null,previewDeparture:null,heroIndex:0,lightboxIndex:0,bookings:[],availability:new Map(),submitting:false};
function seedData(){if(!localStorage.getItem(STORAGE_KEYS.bookings))localStorage.setItem(STORAGE_KEYS.bookings,JSON.stringify(DEFAULT_BOOKINGS));if(!localStorage.getItem(STORAGE_KEYS.requests))localStorage.setItem(STORAGE_KEYS.requests,JSON.stringify([]));}
function getBookings(){try{return JSON.parse(localStorage.getItem(STORAGE_KEYS.bookings)||"[]")}catch{return[]}}
function getRequests(){try{return JSON.parse(localStorage.getItem(STORAGE_KEYS.requests)||"[]")}catch{return[]}}
function setRequests(v){localStorage.setItem(STORAGE_KEYS.requests,JSON.stringify(v));}
function parseISO(iso){const [y,m,d]=iso.split("-").map(Number);return new Date(y,m-1,d);}
function formatISO(date){const y=date.getFullYear(),m=String(date.getMonth()+1).padStart(2,"0"),d=String(date.getDate()).padStart(2,"0");return `${y}-${m}-${d}`;}
function addDays(date,days){const c=new Date(date);c.setDate(c.getDate()+days);return c;}
function formatDate(iso){return parseISO(iso).toLocaleDateString("de-DE",{day:"2-digit",month:"2-digit",year:"numeric"});}
function diffNights(a,b){return Math.round((parseISO(b)-parseISO(a))/86400000);}
function overlaps(startA,endA,startB,endB){return parseISO(startA)<parseISO(endB)&&parseISO(endA)>parseISO(startB);}
function isSameDay(a,b){return formatISO(a)===formatISO(b);}
function expandDateRange(startIso,endIsoInclusive){const dates=[];let c=parseISO(startIso),end=parseISO(endIsoInclusive);while(c<=end){dates.push(formatISO(c));c=addDays(c,1);}return dates;}
function buildAvailability(bookings){const map=new Map();const ensure=iso=>{if(!map.has(iso))map.set(iso,{booked:false,halfStart:false,halfEnd:false});return map.get(iso);};bookings.forEach(booking=>{const start=parseISO(booking.start),end=parseISO(booking.end),lastNight=addDays(end,-1);if(booking.type==="arrival-departure"){ensure(formatISO(start)).halfStart=true;ensure(formatISO(lastNight)).halfEnd=true;}let cursor=new Date(start);while(cursor<end){const iso=formatISO(cursor),st=ensure(iso);if(booking.type==="full")st.booked=true;else if(iso!==formatISO(start)&&iso!==formatISO(lastNight))st.booked=true;cursor=addDays(cursor,1);}});return map;}
function getDayState(iso){const s=state.availability.get(iso);if(!s)return"free";if(s.booked)return"booked";if(s.halfStart)return"half-start";if(s.halfEnd)return"half-end";return"free";}
function isPast(iso){const n=new Date(),t=new Date(n.getFullYear(),n.getMonth(),n.getDate());return parseISO(iso)<t;}
function isSelectable(iso){if(isPast(iso))return false;const st=getDayState(iso);return st!=="booked"&&st!=="half-end";}
function canStayRange(startIso,endIso){if(!startIso||!endIso)return false;if(parseISO(endIso)<=parseISO(startIso))return false;for(const b of state.bookings){if(overlaps(startIso,endIso,b.start,b.end)){if(b.type==="arrival-departure"&&b.start===endIso)continue;if(b.type==="arrival-departure"&&b.end===startIso)continue;return false;}}return true;}
function buildDayMarkers(iso,mini=false){const items=[];if(SPECIAL.school.has(iso))items.push(`<span class="${mini?'mini-dot':'day-marker'} school"></span>`);if(SPECIAL.holiday.has(iso))items.push(`<span class="${mini?'mini-dot':'day-marker'} holiday"></span>`);if(SPECIAL.bridge.has(iso))items.push(`<span class="${mini?'mini-dot':'day-marker'} bridge"></span>`);if(!items.length)return"";return `<span class="${mini?'mini-markers':'day-markers'}">${items.join("")}</span>`;}
function updateSelectionUI(){const arrivalInput=document.getElementById("arrivalInput"),departureInput=document.getElementById("departureInput"),summaryArrival=document.getElementById("summaryArrival"),summaryDeparture=document.getElementById("summaryDeparture"),summaryNights=document.getElementById("summaryNights"),selectionNotice=document.getElementById("selectionNotice");arrivalInput.value=state.selectedArrival?formatDate(state.selectedArrival):"";departureInput.value=state.selectedDeparture?formatDate(state.selectedDeparture):"";summaryArrival.textContent=state.selectedArrival?formatDate(state.selectedArrival):"–";summaryDeparture.textContent=state.selectedDeparture?formatDate(state.selectedDeparture):"–";if(state.selectedArrival&&state.selectedDeparture){summaryNights.textContent=String(diffNights(state.selectedArrival,state.selectedDeparture));selectionNotice.textContent="Zeitraum gewählt.";selectionNotice.className="notice notice-success";}else if(state.selectedArrival){summaryNights.textContent="–";selectionNotice.textContent="Jetzt Abreise wählen.";selectionNotice.className="notice notice-info";}else{summaryNights.textContent="–";selectionNotice.textContent="Anreise wählen, dann Abreise wählen.";selectionNotice.className="notice notice-info";}}
function setPreview(iso){if(!state.selectedArrival||state.selectedDeparture)return;if(parseISO(iso)<=parseISO(state.selectedArrival))return;state.previewDeparture=canStayRange(state.selectedArrival,iso)?iso:null;renderCalendar();}
function clearPreview(){if(!state.previewDeparture)return;state.previewDeparture=null;renderCalendar();}
function handleDateClick(iso){document.getElementById("formError").classList.add("hidden");document.getElementById("formSuccess").classList.add("hidden");if(!isSelectable(iso))return;if(!state.selectedArrival||state.selectedDeparture){state.selectedArrival=iso;state.selectedDeparture=null;state.previewDeparture=null;updateSelectionUI();renderCalendar();return;}if(parseISO(iso)<=parseISO(state.selectedArrival)){state.selectedArrival=iso;state.selectedDeparture=null;state.previewDeparture=null;updateSelectionUI();renderCalendar();return;}if(!canStayRange(state.selectedArrival,iso)){const n=document.getElementById("selectionNotice");n.textContent="Zeitraum nicht verfügbar.";n.className="notice notice-error";state.previewDeparture=null;renderCalendar();return;}state.selectedDeparture=iso;state.previewDeparture=null;updateSelectionUI();renderCalendar();scrollToTarget("#booking");document.getElementById("nameInput").focus();}
function createMonthCard(baseDate){const monthStart=new Date(baseDate.getFullYear(),baseDate.getMonth(),1),monthEnd=new Date(baseDate.getFullYear(),baseDate.getMonth()+1,0),firstWeekday=(monthStart.getDay()+6)%7,today=new Date();const card=document.createElement("article");card.className="month-card";card.innerHTML=`<div class="month-head"><div class="month-title">${monthStart.toLocaleDateString("de-DE",{month:"long",year:"numeric"})}</div></div>`;const weekdays=document.createElement("div");weekdays.className="weekdays";["Mo","Di","Mi","Do","Fr","Sa","So"].forEach(label=>{const n=document.createElement("div");n.className="weekday";n.textContent=label;weekdays.appendChild(n);});card.appendChild(weekdays);const grid=document.createElement("div");grid.className="days-grid";for(let i=0;i<firstWeekday;i++){const s=document.createElement("div");s.className="day-spacer";grid.appendChild(s);}for(let day=1;day<=monthEnd.getDate();day++){const current=new Date(baseDate.getFullYear(),baseDate.getMonth(),day),iso=formatISO(current);const btn=document.createElement("button");btn.type="button";btn.className="day-btn";btn.dataset.date=iso;btn.dataset.state=getDayState(iso);btn.dataset.past=String(isPast(iso));btn.dataset.weekend=String([0,6].includes(current.getDay()));btn.dataset.today=String(isSameDay(current,today));const inRange=state.selectedArrival&&state.selectedDeparture&&parseISO(iso)>parseISO(state.selectedArrival)&&parseISO(iso)<parseISO(state.selectedDeparture);const inPreview=state.selectedArrival&&state.previewDeparture&&parseISO(iso)>parseISO(state.selectedArrival)&&parseISO(iso)<parseISO(state.previewDeparture);if(inRange)btn.dataset.inRange="true";if(inPreview)btn.dataset.preview="true";if(iso===state.selectedArrival)btn.dataset.boundary="start";if(iso===state.selectedDeparture)btn.dataset.boundary="end";if(!isSelectable(iso))btn.disabled=true;btn.innerHTML=`<span class="num">${day}</span>${buildDayMarkers(iso)}`;btn.setAttribute("aria-label",formatDate(iso));btn.addEventListener("pointerenter",()=>setPreview(iso));btn.addEventListener("pointerleave",clearPreview);btn.addEventListener("focus",()=>setPreview(iso));btn.addEventListener("blur",clearPreview);btn.addEventListener("click",()=>handleDateClick(iso));grid.appendChild(btn);}card.appendChild(grid);return card;}
function renderCalendar(){const mount=document.getElementById("calendarMount");if(!mount)return;mount.innerHTML="";const now=new Date();[0,1].forEach(offset=>{const monthDate=new Date(now.getFullYear(),now.getMonth()+state.monthOffset+offset,1);mount.appendChild(createMonthCard(monthDate));});}
function findNextFreeRange(minNights=4){const now=new Date(),horizon=365;for(let offset=0;offset<horizon;offset++){const start=formatISO(addDays(now,offset));if(!isSelectable(start))continue;let length=0;while(offset+length<horizon){const next=formatISO(addDays(now,offset+length+1));if(!canStayRange(start,next))break;length++;if(length>=minNights)return{start,end:next};}}return null;}
function renderNextSlot(){const slot=findNextFreeRange(),box=document.getElementById("nextSlotBox");if(!box)return;if(!slot){box.textContent="Kein längerer freier Zeitraum gefunden.";box.className="notice notice-error";return;}box.textContent=`${formatDate(slot.start)} – ${formatDate(slot.end)} · ${diffNights(slot.start,slot.end)} Nächte`;box.className="notice notice-success";}
function validateForm(){if(!state.selectedArrival||!state.selectedDeparture)return"Bitte zuerst einen Zeitraum wählen.";const name=document.getElementById("nameInput").value.trim(),email=document.getElementById("emailInput").value.trim(),phone=document.getElementById("phoneInput").value.trim();if(!name)return"Bitte Namen eintragen.";if(!email||!email.includes("@"))return"Bitte gültige E-Mail eintragen.";if(!phone||phone.length<6)return"Bitte Telefonnummer eintragen.";return"";}
function setSubmitState(v){state.submitting=v;const btn=document.getElementById("submitBtn");btn.disabled=v;btn.textContent=v?"Wird gesendet …":"Anfrage senden";}
function handleFormSubmit(event){event.preventDefault();if(state.submitting)return;const formError=document.getElementById("formError"),formSuccess=document.getElementById("formSuccess");formError.classList.add("hidden");formSuccess.classList.add("hidden");const error=validateForm();if(error){formError.textContent=error;formError.classList.remove("hidden");return;}setSubmitState(true);const requests=getRequests();requests.unshift({id:crypto.randomUUID?crypto.randomUUID():String(Date.now()),createdAt:new Date().toISOString(),arrival:state.selectedArrival,departure:state.selectedDeparture,nights:diffNights(state.selectedArrival,state.selectedDeparture),name:document.getElementById("nameInput").value.trim(),email:document.getElementById("emailInput").value.trim(),phone:document.getElementById("phoneInput").value.trim(),message:document.getElementById("messageInput").value.trim(),status:"neu"});setRequests(requests);formSuccess.textContent="✓ Anfrage gesendet.";formSuccess.classList.remove("hidden");event.target.reset();state.selectedArrival=null;state.selectedDeparture=null;state.previewDeparture=null;updateSelectionUI();renderCalendar();setSubmitState(false);}
function scrollToTarget(hash,pushHash=false){const target=document.querySelector(hash);if(!target)return;target.scrollIntoView({behavior:"smooth",block:"start"});if(pushHash)history.replaceState(null,"",hash);}
function handleDeepLink(){const hash=location.hash;if(["#booking","#gallery","#top"].includes(hash))setTimeout(()=>scrollToTarget(hash),60);}
function renderMiniGallery(){const el=document.getElementById("miniGallery");if(!el)return;el.innerHTML=PHOTOS.slice(0,3).map((p,i)=>`<button type="button" class="mini-card" data-photo-index="${i}" aria-label="${p.caption}" style="background-image:url('${p.img}')"></button>`).join("");}
function renderMosaic(){const el=document.getElementById("galleryMosaic");if(!el)return;el.innerHTML=PHOTOS.slice(0,7).map((p,i)=>`<button type="button" class="mosaic-tile ${i===0?'large':''}" data-photo-index="${i}" style="background-image:url('${p.img}')"><span class="mosaic-caption">${p.caption}</span></button>`).join("");}
function openLightbox(index){state.lightboxIndex=index;updateLightbox();const lb=document.getElementById("lightbox");lb.classList.add("open");lb.setAttribute("aria-hidden","false");document.body.style.overflow="hidden";}
function closeLightbox(){const lb=document.getElementById("lightbox");lb.classList.remove("open");lb.setAttribute("aria-hidden","true");document.body.style.overflow="";}
function navLightbox(dir){state.lightboxIndex=(state.lightboxIndex+dir+PHOTOS.length)%PHOTOS.length;updateLightbox();}
function updateLightbox(){const p=PHOTOS[state.lightboxIndex];document.getElementById("lightboxImage").style.backgroundImage=`url('${p.img}')`;document.getElementById("lightboxCaption").textContent=`${p.caption} · ${state.lightboxIndex+1}/${PHOTOS.length}`;}
function startHeroRotation(){const a=document.getElementById("heroA"),b=document.getElementById("heroB");if(!a||!b)return;let active=a;setInterval(()=>{state.heroIndex=(state.heroIndex+1)%HERO_IMAGES.length;const next=active===a?b:a;next.style.backgroundImage=`url('${HERO_IMAGES[state.heroIndex]}')`;next.classList.add("active");active.classList.remove("active");active=next;},5200);}
async function loadSpecialDays(){const years=[new Date().getFullYear(),new Date().getFullYear()+1,new Date().getFullYear()+2];years.forEach(y=>(BRIDGE_DAYS[y]||[]).forEach(d=>SPECIAL.bridge.add(d)));const schoolFetches=years.map(y=>fetch(`https://openholidaysapi.org/SchoolHolidays?countryIsoCode=DE&subdivisionCode=DE-NW&languageIsoCode=DE&validFrom=${y}-01-01&validTo=${y}-12-31`).then(r=>r.ok?r.json():[]).catch(()=>[]));const holidayFetches=years.map(y=>fetch(`https://feiertage-api.de/api/?jahr=${y}&nur_land=NW`).then(r=>r.ok?r.json():({})).catch(()=>({})));const schoolResults=await Promise.allSettled(schoolFetches),holidayResults=await Promise.allSettled(holidayFetches);schoolResults.forEach(res=>{if(res.status!=="fulfilled"||!Array.isArray(res.value))return;res.value.forEach(item=>{const start=item.startDate||item.validFrom||item.fromDate,end=item.endDate||item.validTo||item.toDate;if(!start||!end)return;expandDateRange(String(start).slice(0,10),String(end).slice(0,10)).forEach(d=>SPECIAL.school.add(d));});});holidayResults.forEach(res=>{if(res.status!=="fulfilled"||!res.value)return;Object.values(res.value).forEach(item=>{if(item&&item.datum)SPECIAL.holiday.add(item.datum);});});renderCalendar();}
function bindGlobalHandlers(){document.addEventListener("click",event=>{const target=event.target.closest("[data-action],[data-scroll-target],[data-photo-index]");if(!target)return;if(target.dataset.scrollTarget){event.preventDefault();scrollToTarget(target.dataset.scrollTarget,true);return;}if(target.dataset.photoIndex){openLightbox(Number(target.dataset.photoIndex));return;}switch(target.dataset.action){case"prev-months":state.monthOffset-=1;renderCalendar();break;case"next-months":state.monthOffset+=1;renderCalendar();break;default:break;}});const wrap=document.getElementById("calendarWrap");let touchStartX=0;if(wrap){wrap.addEventListener("touchstart",e=>{touchStartX=e.changedTouches[0].clientX;},{passive:true});wrap.addEventListener("touchend",e=>{const delta=e.changedTouches[0].clientX-touchStartX;if(Math.abs(delta)<40)return;state.monthOffset+=delta<0?1:-1;renderCalendar();},{passive:true});}document.getElementById("bookingForm").addEventListener("submit",handleFormSubmit);document.getElementById("lightboxClose").addEventListener("click",closeLightbox);document.getElementById("lightboxPrev").addEventListener("click",()=>navLightbox(-1));document.getElementById("lightboxNext").addEventListener("click",()=>navLightbox(1));document.getElementById("lightbox").addEventListener("click",e=>{if(e.target.id==="lightbox")closeLightbox();});window.addEventListener("hashchange",handleDeepLink);window.addEventListener("load",handleDeepLink);document.addEventListener("keydown",e=>{const open=document.getElementById("lightbox").classList.contains("open");if(!open)return;if(e.key==="Escape")closeLightbox();if(e.key==="ArrowLeft")navLightbox(-1);if(e.key==="ArrowRight")navLightbox(1);});}
function init(){seedData();state.bookings=getBookings();state.availability=buildAvailability(state.bookings);renderMiniGallery();renderMosaic();updateSelectionUI();renderCalendar();renderNextSlot();bindGlobalHandlers();startHeroRotation();loadSpecialDays();}
document.addEventListener("DOMContentLoaded",init);